name: deepspot2cell

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4  # remove if installing CPU-only PyTorch
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - numba
  - llvmlite
  - anndata
  - scanpy
  - squidpy
  - matplotlib
  - pyvips
  - shapely
  - h5py
  - pyyaml

  - pip:
      - -r requirements.txt
